# Generated by Django 5.0 on 2024-06-06 07:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_name', models.CharField(max_length=100)),
                ('app_url', models.CharField(max_length=1000,blank=True, null=True)),
                ('app_username', models.CharField(blank=True, max_length=100, null=True)),
                ('app_password', models.CharField(blank=True, max_length=100, null=True)),
                ('app_two_fa', models.CharField(blank=True, max_length=1000, null=True)),
                ('app_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apps', to=settings.AUTH_USER_MODEL)),
                ('shared_with_groups', models.ManyToManyField(blank=True, related_name='shared_apps', to='auth.group')),
                ('shared_with_users', models.ManyToManyField(blank=True, related_name='shared_apps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
